service: batman # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10

resources:
  Resources:
    rappiprices:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: rappiprices
        AttributeDefinitions:
          - AttributeName: listingId
            AttributeType: S
        KeySchema:
          - AttributeName: listingId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    DynamoDBIamPolicy:
      Type: AWS::IAM::Policy
      DependsOn: rappiprices
      Properties:
        PolicyName: lambda-dynamodb
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:DescribeTable
                - dynamodb:Query
                - dynamodb:Scan
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
              Resource: arn:aws:dynamodb:*:*:table/rappiprices
        Roles:
          - Ref: IamRoleLambdaExecution

functions:
  getprices:
    handler: handler.getprices
  setprices:
    handler: handler.setprices
